import { test, expect } from "@playwright/test";

test("real login, merchant/customer/campaign/coupon/payment, wallet toggles and ES/EN persistence", async ({ page }) => {
  const errors = [];
  page.on("pageerror", e => errors.push(e.message));
  await page.goto("/");
  await page.getByLabel("Usuario", {exact: true}).fill("browser-admin");
  await page.locator('input[type="password"]').fill("wrong");
  await page.getByRole("button", {name: "Entrar", exact: true}).click();
  await expect(page.getByRole("alert")).toBeVisible();
  await page.locator('input[type="password"]').fill("browser-test-password");
  await page.getByRole("button", {name: "Entrar", exact: true}).click();
  await expect(page.getByRole("heading", {name: "Comercios", level: 1})).toBeVisible();
  await page.getByLabel("Idioma").selectOption("en");
  await page.getByLabel("Name", {exact: true}).fill("Browser shop");
  const logo = await page.evaluate(() => {
    const canvas = document.createElement("canvas");
    canvas.width = 32; canvas.height = 32;
    const context = canvas.getContext("2d");
    context.fillStyle = "#123456"; context.fillRect(0, 0, 32, 32);
    return canvas.toDataURL("image/png").split(",")[1];
  });
  await page.getByLabel("Logo", {exact: true}).setInputFiles({ name: "logo.png", mimeType: "image/png", buffer: Buffer.from(logo, "base64") });
  await expect(page.getByAltText("Logo preview")).toBeVisible();
  await page.getByRole("button", {name: "Create", exact: true}).click();
  const merchant = page.getByRole("row").filter({hasText: "Browser shop"});
  await expect(merchant).toBeVisible();
  await page.reload();
  await expect(merchant.getByRole("img")).toBeVisible();
  expect(await merchant.getByRole("img").evaluate(image => image.complete && image.naturalWidth === 32)).toBe(true);
  await merchant.getByRole("button", {name: "Edit", exact: true}).click();
  await page.getByLabel("Name", {exact: true}).fill("Browser cafe");
  await page.getByRole("button", {name: "Save", exact: true}).click();
  const updated = page.getByRole("row").filter({hasText: "Browser cafe"});
  await expect(updated.getByRole("img")).toBeVisible();
  await updated.getByRole("button", {name: "Select", exact: true}).click();
  await page.getByRole("link", {name: "Customers", exact: true}).click();
  await page.getByLabel("Customer code", {exact: true}).fill("BROWSER-C1");
  await page.getByLabel("Email", {exact: true}).fill("browser@example.com");
  await page.getByRole("button", {name: "Enroll", exact: true}).click();
  await expect(page.getByRole("row").filter({hasText: "BROWSER-C1"})).toBeVisible();
  await page.getByRole("link", {name: "Campaigns", exact: true}).click();
  await page.getByLabel("Name", {exact: true}).fill("Browser points campaign");
  await page.getByRole("button", {name: "Create", exact: true}).click();
  await expect(page.getByRole("cell", {name: "Points per spend", exact: true})).toBeVisible();
  await page.getByRole("link", {name: "Coupons", exact: true}).click();
  await page.getByLabel("Customers", {exact: true}).selectOption({label: "BROWSER-C1 \u00b7 browser@example.com"});
  await page.getByRole("button", {name: "Issue coupon", exact: true}).click();
  await expect(page.getByRole("cell", {name: "Issued", exact: true})).toBeVisible();
  await page.getByRole("link", {name: "Payments", exact: true}).click();
  await expect(page.getByLabel("External payment ID")).toHaveCount(0);
  await page.getByLabel("Amount", {exact: false}).fill("25");
  await page.getByLabel("Customer", {exact: true}).selectOption({label: "BROWSER-C1 \u00b7 browser@example.com"});
  await page.getByLabel("Source", {exact: true}).selectOption("getnet");
  const paymentRequest = page.waitForRequest(request => request.url().endsWith("/transactions") && request.method() === "POST");
  await page.getByRole("button", {name: "Record payment"}).click();
  await expect(page.getByRole("status")).toContainText("Balance: 2");
  const firstPayment = (await paymentRequest).postDataJSON();
  expect(firstPayment.source).toBe("getnet");
  expect(firstPayment.identifiers).toEqual({customer_number: "BROWSER-C1"});
  const secondRequest = page.waitForRequest(request => request.url().endsWith("/transactions") && request.method() === "POST");
  await page.getByRole("button", {name: "Record payment"}).click();
  await expect(page.getByRole("status")).toContainText("Balance: 4");
  expect((await secondRequest).postDataJSON().external_transaction_id).not.toBe(firstPayment.external_transaction_id);
  await page.getByRole("link", {name: "Coupons", exact: true}).click();
  await expect(page.getByRole("cell", {name: "Redeemed", exact: true})).toBeVisible();
  await page.getByRole("link", {name: "Customers", exact: true}).click();
  await page.getByRole("button", {name: "Movements", exact: true}).click();
  await expect(page.getByRole("cell", {name: "Points earned", exact: true})).toHaveCount(2);
  await page.getByRole("button", {name: "Wallet passes"}).click();
  await expect(page.getByText("No passes assigned.", {exact: false})).toBeVisible();
  await page.getByRole("link", {name: "Wallet settings", exact: true}).click();
  await page.getByLabel("Certificate password", {exact: true}).fill("synthetic-browser-secret");
  await page.getByLabel("Enabled Apple Wallet").check();
  await page.getByRole("button", {name: "Save Apple Wallet"}).click();
  await expect(page.getByRole("status")).toHaveText("Saved");
  await page.reload();
  await expect(page.getByLabel("Enabled Apple Wallet")).toBeChecked();
  await expect(page.getByLabel("Enabled Google Wallet")).not.toBeChecked();
  await expect(page.getByLabel("Certificate password", {exact: true})).toHaveValue("");
  await page.getByLabel("Enabled Apple Wallet").uncheck();
  await page.getByRole("button", {name: "Save Apple Wallet"}).click();
  await page.getByLabel("Language").selectOption("es");
  await page.getByRole("button", {name: "Salir", exact: true}).click();
  await page.getByLabel("Usuario", {exact: true}).fill("browser-admin");
  await page.locator('input[type="password"]').fill("browser-test-password");
  await page.getByRole("button", {name: "Entrar", exact: true}).click();
  await expect(page.getByRole("heading", {name: "Comercios", level: 1})).toBeVisible();
  await expect(page.getByLabel("Idioma")).toHaveValue("es");
  expect(errors).toEqual([]);
});

test("payment clients follow the merchant and lost responses retry without double accrual", async ({ page, request }) => {
  const login = await request.post("/api/v1/auth/login", {data: {username: "browser-admin", password: "browser-test-password"}});
  const { access_token: token } = await login.json();
  const headers = {Authorization: `Bearer ${token}`};
  await request.patch("/api/v1/users/me", {headers, data: {language: "en"}});
  const first = await (await request.post("/api/v1/merchants", {headers, data: {name: "Retry shop"}})).json();
  const empty = await (await request.post("/api/v1/merchants", {headers, data: {name: "Empty shop"}})).json();
  await request.post(`/api/v1/merchants/${first.id}/customers`, {headers, data: {customer_code: "RETRY-C1"}});
  await request.post(`/api/v1/merchants/${first.id}/campaigns`, {headers, data: {type: "points_per_spend", config: {points: 1, amount_unit: 10}}});
  await page.addInitScript(token => sessionStorage.setItem("token", token), token);
  await page.goto("/transactions");
  await page.getByLabel("Merchant", {exact: true}).selectOption(first.id);
  await page.getByLabel("Customer", {exact: true}).selectOption({label: "RETRY-C1"});
  await page.getByLabel("Amount", {exact: false}).fill("10");
  let original;
  await page.route("**/api/v1/transactions", async route => {
    original = route.request().postDataJSON();
    const committed = await route.fetch();
    expect(committed.ok()).toBe(true);
    await route.abort("failed");
  }, {times: 1});
  await page.getByRole("button", {name: "Record payment"}).click();
  await expect(page.getByRole("alert")).toBeVisible();
  const retry = page.waitForRequest(request => request.url().endsWith("/transactions") && request.method() === "POST");
  await page.getByRole("button", {name: "Record payment"}).click();
  await expect(page.getByRole("status")).toContainText("already recorded");
  expect((await retry).postDataJSON().external_transaction_id).toBe(original.external_transaction_id);
  const customers = await (await request.get(`/api/v1/merchants/${first.id}/customers`, {headers})).json();
  expect(customers[0].points_balance).toBe(1);
  await page.getByLabel("Merchant", {exact: true}).selectOption(empty.id);
  await expect(page.getByText("Enroll a customer in this merchant to simulate a payment.")).toBeVisible();
  await expect(page.getByLabel("Customer", {exact: true}).getByRole("option")).toHaveCount(1);
  await expect(page.getByRole("button", {name: "Record payment"})).toBeDisabled();
  await expect(page.getByRole("status")).toHaveCount(0);
  await page.getByLabel("Merchant", {exact: true}).selectOption(first.id);
  await expect(page.getByLabel("Customer", {exact: true})).toHaveValue("");
  await expect(page.getByLabel("Amount", {exact: false})).toHaveValue("");
});

test("campaign pass assignment shows URL and QR and supports parent deletions", async ({ page, request }) => {
  const response = await request.post("/api/v1/auth/login", {data: {username: "browser-admin", password: "browser-test-password"}});
  const {access_token: token} = await response.json();
  const headers = {Authorization: `Bearer ${token}`};
  await request.patch("/api/v1/users/me", {headers, data: {language: "en"}});
  const merchant = await (await request.post("/api/v1/merchants", {headers, data: {name: "Campaign pass shop"}})).json();
  const enrolled = await (await request.post(`/api/v1/merchants/${merchant.id}/customers`, {headers, data: {customer_code: "PASS-C1"}})).json();
  const customer = enrolled.customer;
  const campaigns = [];
  for (const name of ["Coffee rewards", "Lunch rewards"]) {
    campaigns.push(await (await request.post(`/api/v1/merchants/${merchant.id}/campaigns`, {headers, data: {name, type: "points_per_spend", config: {points: 1, amount_unit: 10}}})).json());
  }
  await request.put("/api/v1/settings/wallet/google", {headers, data: {enabled: true, config: {issuer_id: "123", sa_json: "__missing_browser_test_credentials__"}}});
  // Keep real assignment persistence and authorization; substitute only provider delivery.
  await page.route(`**/customers/${customer.id}/passes`, async route => {
    if (route.request().method() !== "POST") return route.continue();
    const response = await route.fetch();
    expect(response.ok()).toBe(true);
    const body = await response.json();
    await route.fulfill({response, json: {...body, provider_synced: true, url: `https://pay.google.com/gp/v/save/browser-${body.pass.id}`}});
  });
  await page.addInitScript(token => sessionStorage.setItem("token", token), token);
  await page.goto("/passes");
  await page.getByLabel("Merchant", {exact: true}).selectOption(merchant.id);
  for (const campaign of campaigns) {
    await page.getByLabel("Campaign", {exact: true}).selectOption(campaign.id);
    await page.getByLabel("Customer", {exact: true}).selectOption(customer.id);
    await page.getByRole("button", {name: "Assign pass", exact: true}).click();
    await expect(page.getByLabel("Enrollment URL")).toHaveValue(/https:\/\/pay.google.com\/gp\/v\/save\/browser-/);
    await expect(page.getByAltText("Wallet enrollment QR")).toBeVisible();
    expect(await page.getByAltText("Wallet enrollment QR").getAttribute("src")).toMatch(/^data:image\/png;base64,/);
  }
  await expect(page.getByRole("row").filter({hasText: "PASS-C1"})).toHaveCount(2);
  page.on("dialog", dialog => dialog.accept());
  await page.getByRole("row").filter({hasText: "Coffee rewards"}).getByRole("button", {name: "Delete", exact: true}).click();
  await expect(page.getByRole("status")).toContainText("revocation is pending");
  await expect(page.getByRole("row").filter({hasText: "Coffee rewards"})).toContainText("Deleted");
  await page.getByRole("link", {name: "Campaigns", exact: true}).click();
  await page.getByRole("row").filter({hasText: "Lunch rewards"}).getByRole("button", {name: "Delete", exact: true}).click();
  await expect(page.getByRole("row").filter({hasText: "Lunch rewards"})).toHaveCount(0);
  await page.getByRole("link", {name: "Customers", exact: true}).click();
  await page.getByRole("row").filter({hasText: "PASS-C1"}).getByRole("button", {name: "Delete", exact: true}).click();
  await expect(page.getByRole("row").filter({hasText: "PASS-C1"})).toHaveCount(0);
  await page.getByRole("link", {name: "Wallet passes", exact: true}).click();
  await expect(page.getByRole("row").filter({hasText: "PASS-C1"})).toHaveCount(2);
  await expect(page.getByRole("button", {name: "Retry revocation"})).toHaveCount(2);
  await request.put("/api/v1/settings/wallet/google", {headers, data: {enabled: false}});
});


test("merchant deletion previews impact, cancels safely and confirms cascade", async ({ page, request }) => {
  const response = await request.post("/api/v1/auth/login", {data: {username: "browser-admin", password: "browser-test-password"}});
  const {access_token: token} = await response.json();
  const headers = {Authorization: `Bearer ${token}`};
  await request.patch("/api/v1/users/me", {headers, data: {language: "en"}});
  const merchant = await (await request.post("/api/v1/merchants", {headers, data: {name: "Delete cascade shop"}})).json();
  await request.post(`/api/v1/merchants/${merchant.id}/customers`, {headers, data: {customer_code: "DELETE-C1"}});
  await request.post(`/api/v1/merchants/${merchant.id}/campaigns`, {headers, data: {name: "Deletion campaign", type: "interaction", config: {interactions_required: 5, reward_description: "Free coffee"}}});
  await page.addInitScript(token => sessionStorage.setItem("token", token), token);
  await page.goto("/merchants");
  const row = page.getByRole("row").filter({hasText: "Delete cascade shop"});
  await row.getByRole("button", {name: "Delete", exact: true}).click();
  const dialog = page.getByRole("dialog");
  await expect(dialog).toContainText("Delete cascade shop");
  await expect(dialog).toContainText("History retained");
  await expect(dialog.locator(".deletion-summary > div").filter({hasText: "Customers"})).toContainText("1");
  await expect(dialog.locator(".deletion-summary > div").filter({hasText: "Campaigns"})).toContainText("1");
  await page.screenshot({path: "test-results/merchant-deletion-desktop.png", fullPage: true});
  await dialog.getByRole("button", {name: "Cancel", exact: true}).click();
  await expect(row).toBeVisible();
  await page.setViewportSize({width: 390, height: 844});
  await row.getByRole("button", {name: "Delete", exact: true}).click();
  await expect(dialog).toBeVisible();
  await page.screenshot({path: "test-results/merchant-deletion-mobile.png", fullPage: true});
  await dialog.getByRole("button", {name: "Confirm deletion", exact: true}).click();
  await expect(row).toHaveCount(0);
  await expect(page.getByRole("status")).toContainText("Merchant deleted");
  expect((await request.get(`/api/v1/merchants/${merchant.id}/customers`, {headers})).status()).toBe(404);
  const docs = await request.get("/docs");
  expect(docs.status()).toBe(200);
  expect(await docs.text()).toContain("swagger-ui");
});
