import { test, expect } from "@playwright/test";
import { fillDesign, png } from "./campaign-fixtures";

test("designer previews, validates, recovers upload errors and edits campaign memberships on mobile", async ({ page, request }) => {
  const login = await request.post("/api/v1/auth/login", {data: {username: "browser-admin", password: "browser-test-password"}});
  const {access_token: token} = await login.json();
  const headers = {Authorization: `Bearer ${token}`};
  await request.patch("/api/v1/users/me", {headers, data: {language: "en"}});
  const merchant = await (await request.post("/api/v1/merchants", {headers, data: {name: "Designer bakery"}})).json();
  const person = await (await request.post(`/api/v1/merchants/${merchant.id}/customers`, {headers, data: {name: "Real customer", customer_code: "REAL-1"}})).json();
  await page.addInitScript(token => sessionStorage.setItem("token", token), token);
  await page.goto("/campaigns");
  await page.getByLabel("Merchant", {exact: true}).selectOption(merchant.id);
  await page.getByRole("button", {name: "New campaign", exact: true}).click();
  await page.getByLabel("Name", {exact: true}).fill("Bakery rewards");
  await expect(page.getByRole("figure", {name: "Pass preview"})).toHaveCount(2);
  await expect(page.getByRole("figure").first()).toContainText("Example customer");
  await expect(page.getByRole("figure").first()).toContainText("320");
  await page.getByLabel("Accessible logo description").fill("Logo");
  await page.getByLabel("Accessible hero description").fill("Banner");
  await page.getByLabel("I have reviewed", {exact: false}).check();
  await page.getByRole("button", {name: "Create", exact: true}).click();
  await expect(page.getByRole("alert")).toContainText("Upload both");
  await page.getByLabel("Pass logo", {exact: true}).setInputFiles({name: "invalid.png", mimeType: "image/png", buffer: Buffer.from("not an image")});
  await expect(page.getByRole("alert")).toContainText("Invalid image");
  let release;
  const paused = new Promise(resolve => {release = resolve;});
  await page.route("**/pass-assets", async route => {await paused; await route.continue();}, {times: 1});
  await page.getByLabel("Pass logo", {exact: true}).setInputFiles({name: "logo.png", mimeType: "image/png", buffer: png});
  await expect(page.getByRole("status")).toContainText("Saving images");
  await expect(page.getByRole("button", {name: "Create", exact: true})).toBeDisabled();
  release();
  await expect(page.getByLabel("Accessible logo description")).toBeEnabled();
  await fillDesign(page);
  await page.getByLabel("Hexadecimal color", {exact: false}).fill("bad");
  expect(await page.getByLabel("Hexadecimal color", {exact: false}).evaluate(e => e.checkValidity())).toBe(false);
  await page.getByLabel("Hexadecimal color", {exact: false}).fill("#123456");
  await expect(page.locator(".wallet-card").first()).toHaveCSS("background-color", "rgb(18, 52, 86)");
  await page.getByLabel("I have reviewed", {exact: false}).check();
  await page.getByRole("button", {name: "Create", exact: true}).click();
  const row = page.getByRole("row").filter({hasText: "Bakery rewards"});
  await expect(row).toBeVisible();
  const [campaign] = await (await request.get(`/api/v1/merchants/${merchant.id}/campaigns`, {headers})).json();
  expect(campaign.design.background_color).toBe("#123456");
  expect(await (await request.get(`/api/v1/campaigns/${campaign.id}/customers`, {headers})).json()).toEqual([]);
  expect((await request.get(new URL(campaign.design.logo_url).pathname)).status()).toBe(200);
  await row.getByRole("button", {name: "Edit", exact: true}).click();
  await page.setViewportSize({width: 390, height: 844});
  await expect(page.getByAltText("Merchant logo").first()).toBeVisible();
  await page.getByLabel("Search customers").fill("Real");
  await page.getByLabel("Real customer (REAL-1)", {exact: true}).check();
  await page.screenshot({path: "test-results/campaign-designer-mobile.png", fullPage: true});
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.getByLabel("I have reviewed", {exact: false}).check();
  await page.getByRole("button", {name: "Save", exact: true}).click();
  await expect(row).toBeVisible();
  const members = await (await request.get(`/api/v1/campaigns/${campaign.id}/customers`, {headers})).json();
  expect(members).toHaveLength(1); expect(members[0].customer_id).toBe(person.customer.id); expect(members[0].points_balance).toBe(0);
  await row.getByRole("button", {name: "Edit", exact: true}).click();
  await expect(page.getByText("Previously enrolled", {exact: true})).toBeVisible();
  await page.setViewportSize({width: 1280, height: 900});
  await page.screenshot({path: "test-results/campaign-designer-desktop.png", fullPage: true});
  page.on("dialog", dialog => dialog.accept());
  await page.getByRole("button", {name: "Suspend", exact: true}).click();
  await expect(page.getByRole("cell", {name: "Suspended", exact: true})).toBeVisible();
});
