import { test, expect } from "@playwright/test";
import { fillDesign } from "./campaign-fixtures";

test("public API allows anonymous calls while admin requires login and saves complete design", async ({page, request}) => {
  test.skip(process.env.BROWSER_AUTH_ENABLED !== "false", "Run with BROWSER_AUTH_ENABLED=false");
  await page.addInitScript(() => localStorage.setItem("lang", "en"));
  await page.goto("/");
  await expect(page.getByRole("button", {name: "Sign in", exact: true})).toBeVisible();
  expect((await request.get("/api/v1/users/me")).status()).toBe(401);
  const merchant = await (await request.post("/api/v1/merchants", {data: {name: "Open demo store"}})).json();
  await page.getByLabel("Username", {exact: true}).fill("browser-admin");
  await page.getByLabel("Password", {exact: true}).fill("incorrect-password");
  await page.getByRole("button", {name: "Sign in", exact: true}).click();
  await expect(page.getByRole("alert")).toBeVisible();
  await page.getByLabel("Password", {exact: true}).fill("browser-test-password");
  await page.getByRole("button", {name: "Sign in", exact: true}).click();
  // Language is stored per authenticated admin, whose default is Spanish.
  await page.getByLabel(/Idioma|Language/).selectOption("en");
  await expect(page.getByRole("heading", {name: "Merchants", level: 1, exact: true})).toBeVisible();
  expect(await page.evaluate(() => sessionStorage.getItem("token"))).toBeTruthy();
  await page.getByRole("link", {name: "Customers", exact: true}).click();
  await page.getByLabel("Merchant", {exact: true}).selectOption(merchant.id);
  await page.getByLabel("Customer name", {exact: true}).fill("Open customer");
  await page.getByLabel("Customer code", {exact: true}).fill("OPEN-UI");
  await page.getByLabel("Customer joining date", {exact: true}).fill("2023-07-10");
  await page.getByRole("button", {name: "Enroll", exact: true}).click();
  await expect(page.getByRole("row").filter({hasText: "OPEN-UI"})).toContainText("2023");
  const [customer] = await (await request.get(`/api/v1/merchants/${merchant.id}/customers`)).json();
  expect(customer.created_at).toMatch(/^2023-07-10/);
  await page.getByRole("link", {name: "Campaigns", exact: true}).click();
  await page.getByRole("button", {name: "New campaign", exact: true}).click();
  await page.getByLabel("Name", {exact: true}).fill("Complete public design");
  await fillDesign(page);
  await expect(page.getByLabel("Pass title", {exact: true})).toHaveValue("Open demo store");
  await page.getByLabel("Points label", {exact: true}).fill("Rewards");
  await page.getByLabel("Customer since label", {exact: true}).fill("Member since");
  await page.getByLabel("Text below QR", {exact: true}).fill("Show this code");
  await expect(page.getByRole("figure").first()).toContainText("Sep 2026");
  await expect(page.getByRole("figure").first()).toContainText("Show this code");
  await page.getByLabel("Open customer (OPEN-UI)", {exact: true}).check();
  await page.getByLabel("I have reviewed", {exact: false}).check();
  await page.getByRole("button", {name: "Create", exact: true}).click();
  await expect(page.getByRole("row").filter({hasText: "Complete public design"})).toBeVisible();
  const [campaign] = await (await request.get(`/api/v1/merchants/${merchant.id}/campaigns`)).json();
  expect(campaign.design.points_label).toBe("Rewards");
  expect(campaign.design.member_since_label).toBe("Member since");
  expect(campaign.design.barcode_alternate_text).toBe("Show this code");
  expect((await request.get(new URL(campaign.design.hero_url).pathname)).ok()).toBe(true);
  await page.reload();
  await expect(page.getByRole("button", {name: "Log out", exact: true})).toBeVisible();
  await page.getByRole("button", {name: "Log out", exact: true}).click();
  await expect(page.getByRole("button", {name: "Sign in", exact: true})).toBeVisible();
  expect(await page.evaluate(() => sessionStorage.getItem("token"))).toBeNull();
  await page.goto("/campaigns");
  await expect(page.getByRole("button", {name: "Sign in", exact: true})).toBeVisible();
  expect((await request.get("/api/v1/merchants")).ok()).toBe(true);
});
